sudo: false
language: node_js
node_js:
 - node
cache: npm
branches:
  only:
  - master
before_script:
  - npm install yaspeller -g
script:
  - yaspeller --only-errors -c common-configs/.yaspellerrc ru/**/*.md
